/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AuthPage: typeof import('./components/AuthPage.vue')['default']
    BillingForm: typeof import('./components/BillingForm.vue')['default']
    Carousels: typeof import('./components/Carousels.vue')['default']
    CartList: typeof import('./components/CartList.vue')['default']
    ChatBot: typeof import('./components/ChatBot.vue')['default']
    CustomPartSideBar: typeof import('./components/CustomPartSideBar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GlitchGif: typeof import('./components/GlitchGif.vue')['default']
    GMap: typeof import('./components/GMap.vue')['default']
    ImageCarousel: typeof import('./components/ImageCarousel.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    LoginOverlay: typeof import('./components/LoginOverlay.vue')['default']
    MapBox: typeof import('./components/MapBox.vue')['default']
    MapDisplay: typeof import('./components/MapDisplay.vue')['default']
    OrderHistory: typeof import('./components/OrderHistory.vue')['default']
    OrderSummary: typeof import('./components/OrderSummary.vue')['default']
    PaymentMethod: typeof import('./components/PaymentMethod.vue')['default']
    ProductInfoSideBar: typeof import('./components/ProductInfoSideBar.vue')['default']
    ProductPanel: typeof import('./components/ProductPanel.vue')['default']
    ProductsPanel: typeof import('./components/ProductsPanel.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopItem: typeof import('./components/ShopItem.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    'Terms&Conditions': typeof import('./components/Terms&Conditions.vue')['default']
    ThreeCanvas: typeof import('./components/ThreeCanvas.vue')['default']
  }
}
