/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BarChart: typeof import('./components/BarChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    MultipleLineChart: typeof import('./components/MultipleLineChart.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    Plotlygauge: typeof import('./components/PlotlyGauge.vue')['default']
    PlotlyGauge: typeof import('./components/PlotlyGauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunburstChart: typeof import('./components/SunburstChart.vue')['default']
    VueGauge: typeof import('./components/VueGauge.vue')['default']
  }
}
